adding settings and configurations to send the message to anyone
guptahemant/insta-clone pull request #126
Opened 2022-04-17 17:18 UTC by sharayu0

2022-04-18 19:03 UTC, sharayu0 commented
Message sent from one user to another or between active user is done properly.

2022-04-19 17:23 UTC, sharayu0 commented
was trying to use the view to display private message thread of the member users but not worked for the user to display recepient user to which current user sending message.
worked on Customized private message threads, Customized private messages , Customized the display of thread members.

2022-04-20 04:23 UTC, JayKandari requested changes

2022-04-20 04:23 UTC, JayKandari commented on web/sites/default/settings.php
> +    '8IgDpLP4DIfk_J3udJe68AMGdUukbgOo5RpnuE1KIQQi-jQLGT5D2CbXZGnUY6PvA3yV10Qs8Q';
Is this change required ? if not can we remove this.

2022-04-20 18:58 UTC, JatinGupta40 approved these changes

2022-04-21 04:16 UTC, JayKandari approved these changes
LGTM.

2022-04-21 08:21 UTC, merged