Added footer in 4-Footer
guptahemant/insta-clone pull request #35
Opened 2021-12-14 10:11 UTC by pritamyj

Added footer
- added footer.css
- added page.html.twig file

2021-12-15 04:30 UTC, guptahemant commented
Ignore the contrib modules / themes from github

2021-12-15 04:34 UTC, guptahemant commented on web/sites/default/settings.php
> +);
Move this to settings.local.php so that this is not reflected in settings.php

2021-12-15 04:35 UTC, guptahemant commented on web/themes/custom/instagram/css/all/footer.css
> +.pC2e0{
ignore generated Css files because they will be generated on local by executing gulp tasks.

2021-12-15 04:39 UTC, guptahemant requested changes
Please check review comments

2021-12-16 11:18 UTC, VighneshSadagopal approved these changes

2021-12-16 11:21 UTC, VighneshSadagopal submitted a review, later dismissed
changes reviewed

2021-12-16 18:33 UTC, VighneshSadagopal approved these changes

2021-12-16 20:28 UTC, closed without merging