36-slider-image
guptahemant/insta-clone pull request #47
Opened 2022-01-01 16:26 UTC by atulghate

2022-01-02 07:54 UTC, sharayu0 submitted a review, later dismissed

2022-01-04 04:18 UTC, guptahemant requested changes
@atulghate please revert the language file changes.
Re-setup local with proper config setup

@sharayu0 do not approve PR without reviewing what has changed

2022-01-04 11:30 UTC, VighneshSadagopal approved these changes

2022-01-04 11:43 UTC, guptahemant approved these changes

2022-01-04 11:43 UTC, merged