Resolved some coding standard issue in the modules and themes file
guptahemant/insta-clone pull request #77
Opened 2022-02-14 13:40 UTC by VighneshSadagopal

Resolved some coding standard issue for modules and themes folder.

2022-02-14 13:59 UTC, sharayu0 commented on web/modules/custom/log_mod/src/Controller/TestController.php
> -?>
Add new line at the end of file after ?> tag and also check for remaining files

2022-02-14 14:08 UTC, sharayu0 commented on web/modules/custom/demo_con/demo_con.info.yml
> -  - default_content:default_content
Add new line at the end of file and also check for remaining files

2022-02-14 14:28 UTC, JatinGupta40 requested changes

2022-02-14 14:28 UTC, JatinGupta40 commented on web/modules/custom/log_mod/log_mod.module
> +      ],
The brace should move 2 steps to the left (straight below the $ of line 42).

2022-02-15 03:54 UTC, sharayu0 approved these changes

2022-02-15 03:55 UTC, merged

2022-02-15 04:43 UTC, guptahemant commented on web/modules/custom/log_mod/log_mod.module
> + * Returns the variable from the custom block.
Hook implementations needs a different functional doc, Please add them as per official documentation.

2022-02-15 04:43 UTC, guptahemant commented on web/modules/custom/log_mod/log_mod.module
> + * Alter the login form.
Same here.

2022-02-15 04:43 UTC, guptahemant commented on web/modules/custom/profile_block/profile_block.module
> + * To store the variable in the user profile block.
Same here.